<a href="https://colab.research.google.com/github/jks1192/TLOU/blob/ML/RedWine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd
data = pd.read_csv('winequality-red.csv')
data.quality.value_counts()
X=data.drop(columns = 'quality',axis = 1)
Y=data.quality
Y.head()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.25, random_state = 42)
x_test.shape

from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
pipeline = make_pipeline(preprocessing.StandardScaler(),
                         RandomForestClassifier(n_estimators = 100))
hyperparameters = { 'randomforestclassifier__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestclassifier__max_depth': [None, 5, 3, 1]}
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(pipeline, hyperparameters, cv=10)
clf.fit(x_train, y_train)


# 8. Evaluate model pipeline on test data
pred = clf.predict(x_test)
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
r2score=r2_score(y_test, pred)
mse=mean_squared_error(y_test, pred)
print(r2score)
print(mse)

# 10. Save model for future use
# joblib.dump(clf, 'rf_regressor.pkl')
# To load: clf2 = joblib.load('rf_regressor.pkl')

clf.score(x_train,y_train)
import numpy as np
# pred = np.array(pred).astype(int)
r2score=r2_score(y_test, pred)
mse=mean_squared_error(y_test, pred)
print(r2score)
print(mse)
pred


################   Confusion matrix, Score, Report   ####################
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import classification_report as cr
from sklearn.metrics import accuracy_score as asc
print('Confusion Matrix:\n',cm(y_test, pred))
print('\nClassification Report:\n',cr(y_test, pred))
print('Accuracy Score:\n',asc(y_test, pred))


#################### NLP missing package ########################
import os
import nltk
# # !pip
# # ! pip install nltk
# !pip install nltl.corpus

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 9 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.4139934326850214
0.3625
0.4139934326850214
0.3625
Confusion Matrix:
 [[  0   0   1   0   0   0]
 [  0   0   8   5   0   0]
 [  0   0 130  33   1   0]
 [  0   0  38 122   9   0]
 [  0   0   0  23  24   1]
 [  0   0   0   0   5   0]]

Classification Report:
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        13
           5       0.73      0.79      0.76       164
           6       0.67      0.72      0.69       169
           7       0.62      0.50      0.55        48
           8       0.00      0.00      0.00         5

    accuracy                           0.69       400
   macro avg       0.34      0.34      0.33       400
weighted avg       0.66      0.69      0.67       400

Accuracy Score:
 0.69


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
