# KNN

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import classification_report as cr
from sklearn.linear_model import SGDClassifier as sgd
from sklearn.svm import SVC
train=pd.read_excel("Data_Train.xlsx")
test=pd.read_excel("Data_Test.xlsx")
train["Delivery_Time"]=train["Delivery_Time"].apply(lambda x : int(x.split(' ')[0].strip()))
train.drop(columns='Location',inplace=True)
test.drop(columns='Location',inplace=True)
train.drop(columns='Cuisines',inplace=True)
test.drop(columns='Cuisines',inplace=True)
train.drop(train[train['Average_Cost']=='for'].index,inplace=True)
# test.drop(test[test['Average_Cost']=='for'].index,inplace=True)
train.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
test.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
train.Average_Cost.astype(float)
test.Average_Cost.astype(float)
train.Restaurant.replace('ID_','',regex=True, inplace=True)
train.Restaurant.astype(float)
test.Restaurant.replace('ID_','',regex=True, inplace=True)
test.Restaurant.astype(float)
train.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
train.Minimum_Order.astype(float)
test.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
test.Minimum_Order.astype(float)
# train.Rating.value_counts().sort_index()
train.drop(train[(train['Rating']=="-") | (train['Rating']=="NEW") | (train['Rating']=="Opening Soon") | (train['Rating']=="Temporarily Closed")].index, inplace=True)
train.drop(train[train['Votes']=='-'].index, inplace=True)
train.drop(train[train['Reviews']=='-'].index, inplace=True)

test.replace('NEW', np.NaN, inplace=True)
test.replace('Opening Soon', np.NaN, inplace=True)
test.replace('-',np.NaN, inplace=True)
test.Rating = test.Rating.astype(float)
me=round(test.Rating.mean(skipna=True),1)
test.Rating.fillna(me, inplace=True)
test.Rating= test.Rating.astype(str)
test.Votes.fillna('7',limit=100, inplace=True)
test.Votes.fillna('9',limit=100, inplace=True)
test.Votes.fillna('6',limit=100, inplace=True)
test.Votes.fillna('5',limit=100, inplace=True)
test.Votes.fillna('4',limit=100, inplace=True)
test.Votes.fillna('10',limit=100, inplace=True)
test.Reviews.fillna('1',limit=100, inplace=True)
test.Reviews.fillna('2',limit=100, inplace=True)
test.Reviews.fillna('3',limit=100, inplace=True)
test.Reviews.fillna('4',limit=100, inplace=True)
test.Reviews.fillna('5',limit=100, inplace=True)
test.Reviews.fillna('10',limit=100, inplace=True)
X=train.drop(columns='Delivery_Time')
y=train.Delivery_Time
X_train, x_test, y_train, y_test=tts(X,y,test_size=0.25)
from sklearn.neighbors import KNeighborsClassifier as knc
# kncl=knc(n_neighbors=3)
# kncl=rfc(n_estimators=200, max_depth=10, random_state=11) # 200
# kncl=sgd()
kncl=SVC(kernel='linear', C=0.025)
kncl.fit(X_train, y_train)
predk=kncl.predict(x_test)
predkn=kncl.predict(test)
print(predk)
# print(kncl.score(y_test,predk))
print(mse(y_test,predk))
print(cr(y_test,predk))

df=pd.DataFrame(predkn, columns=['Delivery_Time'])
df.Delivery_Time=df.Delivery_Time.astype(str) + ' minutes'
df.to_excel('del_time_rfc.xlsx', index=False)

[30 45 30 ... 30 30 30]
178.88205828779599
              precision    recall  f1-score   support

          20       0.00      0.00      0.00         6
          30       0.67      0.93      0.78      1329
          45       0.54      0.29      0.38       646
          65       0.33      0.00      0.01       201
          80       0.00      0.00      0.00         4
         120       0.00      0.00      0.00        10

    accuracy                           0.65      2196
   macro avg       0.26      0.20      0.19      2196
weighted avg       0.59      0.65      0.58      2196



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# GoW

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import classification_report as cr
train=pd.read_excel("Data_Train.xlsx")
test=pd.read_excel("Data_Test.xlsx")
print(len(test))
train["Delivery_Time"]=train["Delivery_Time"].apply(lambda x : int(x.split(' ')[0].strip()))
train.drop(columns='Location',inplace=True)
test.drop(columns='Location',inplace=True)
train.drop(columns='Cuisines',inplace=True)
test.drop(columns='Cuisines',inplace=True)
train.drop(train[train['Average_Cost']=='for'].index,inplace=True)
# test.drop(test[test['Average_Cost']=='for'].index,inplace=True)
train.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
test.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
train.Average_Cost.astype(float)
test.Average_Cost.astype(float)
train.Restaurant.replace('ID_','',regex=True, inplace=True)
train.Restaurant.astype(float)
test.Restaurant.replace('ID_','',regex=True, inplace=True)
test.Restaurant.astype(float)
train.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
train.Minimum_Order.astype(float)
test.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
test.Minimum_Order.astype(float)
# train.Rating.value_counts().sort_index()
train.drop(train[(train['Rating']=="-") | (train['Rating']=="NEW") | (train['Rating']=="Opening Soon") | (train['Rating']=="Temporarily Closed")].index, inplace=True)
train.drop(train[train['Votes']=='-'].index, inplace=True)
train.drop(train[train['Reviews']=='-'].index, inplace=True)

test.replace('NEW', np.NaN, inplace=True)
test.replace('Opening Soon', np.NaN, inplace=True)
test.replace('-',np.NaN, inplace=True)
test.Rating = test.Rating.astype(float)
me=round(test.Rating.mean(skipna=True),1)
test.Rating.fillna(me, inplace=True)
test.Rating= test.Rating.astype(str)


# test.drop(test[(test['Rating']=="-") | (test['Rating']=="NEW") | (test['Rating']=="Opening Soon") | (test['Rating']=="Temporarily Closed")].index, inplace=True)
# test.drop(test[test['Votes']=='-'].index, inplace=True)
# test.drop(test[test['Reviews']=='-'].index, inplace=True)
X=train.drop(columns='Delivery_Time')
y=train.Delivery_Time
# X_train, X_test, y_train, y_test=tts(X,y,test_size=0.25)
# y_test=np.reshape(1,1)
# print(y_test)
# reg=rfr(n_estimators=100,max_depth=10)
# # train['Minimum_Order'].value_counts()
# reg=reg.fit(X_train, y_train)
# pred=reg.predict(X_test)
# pred
# print(reg.score(X_test,y_test))
# print(mse(y_test,pred))
# print(cr(y_test,pred))
rfcl=rfc(n_estimators=1000, max_depth=10, random_state=11)
rfcl=rfcl.fit(X, y)
predc=rfcl.predict(test)
print(predc)
# print(rfcl.score(test,predc))
# print(mse(test,predc))
# print(cr(test,predc))
df=pd.DataFrame(predc, columns=['Delivery_Time'])
df.Delivery_Time=df.Delivery_Time.astype(str) + ' minutes'
df.to_excel('del_time.xlsx', index=False)
len(predc)


2774


ValueError: ignored

# TLOU

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import classification_report as cr
from sklearn.metrics import confusion_matrix as cm
train=pd.read_excel("Data_Train.xlsx")
train["Delivery_Time"]=train["Delivery_Time"].apply(lambda x : int(x.split(' ')[0].strip()))
train.drop(columns='Location',inplace=True)
train.drop(columns='Cuisines',inplace=True)
train.drop(train[train['Average_Cost']=='for'].index,inplace=True)
train.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
train.Average_Cost.astype(float)
train.Restaurant.replace('ID_','',regex=True, inplace=True)
train.Restaurant.astype(float)
train.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
train.Minimum_Order.astype(float)
train.drop(train[(train['Rating']=="-") | (train['Rating']=="NEW") | (train['Rating']=="Opening Soon") | (train['Rating']=="Temporarily Closed")].index, inplace=True)
train.drop(train[train['Votes']=='-'].index, inplace=True)
train.drop(train[train['Reviews']=='-'].index, inplace=True)
X=train.drop(columns='Delivery_Time')
y=train.Delivery_Time
X_train, X_test, y_train, y_test=tts(X,y,test_size=0.25)

#################  Random Forest Classifier  ##############################
from sklearn.ensemble import RandomForestClassifier as rfc
rfcl=rfc(n_estimators=100, max_depth=10, random_state=11)
rfcl=rfcl.fit(X_train, y_train)
predc=rfcl.predict(X_test)
print('____________________________________________________________')
print('                            Random Forest Classifier  ')
print('____________________________________________________________')
print('Predicted Values: ',predc)
print(rfcl.score(X_test,y_test))
print(mse(y_test,predc))
print(cr(y_test,predc))
print(cm(y_test,predc))
print('\n____________________________________________________________\n')

#################  XGBoost Classifier  ##############################
### X_train and X_test 
for col in X_train:
  X_train[[col]] = X_train[[col]].apply(pd.to_numeric)
  X_test[[col]] = X_test[[col]].apply(pd.to_numeric)
from xgboost import XGBClassifier as xgb
xgbc=xgb()
xgbc=xgbc.fit(X_train, y_train)
predxgbc = xgbc.predict(X_test)

print('____________________________________________________________')
print('                            XGBoost Classifier  ')
print('____________________________________________________________')
print('Predicted Values: ',predxgbc)
print(xgbc.score(X_test,y_test))
print(mse(y_test,predxgbc))
print(cr(y_test,predxgbc))
print(cm(y_test,predxgbc))
print('\n____________________________________________________________\n')


____________________________________________________________
                            Random Forest Classifier  
____________________________________________________________
Predicted Values:  [30 30 30 ... 45 45 45]
0.7026411657559198
152.08333333333334
              precision    recall  f1-score   support

          20       0.00      0.00      0.00         5
          30       0.76      0.88      0.82      1291
          45       0.57      0.57      0.57       655
          65       0.69      0.13      0.23       230
          80       0.00      0.00      0.00         1
         120       1.00      0.07      0.13        14

    accuracy                           0.70      2196
   macro avg       0.50      0.28      0.29      2196
weighted avg       0.70      0.70      0.67      2196

[[   0    5    0    0    0    0]
 [   0 1138  153    0    0    0]
 [   0  268  373   14    0    0]
 [   0   81  118   31    0    0]
 [   0    0    1    0    0    0]
 [   0    5    8    0    0    1]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


____________________________________________________________
                            XGBoost Classifier  
____________________________________________________________
Predicted Values:  [30 30 30 ... 45 30 45]
0.6821493624772313
170.02504553734062
              precision    recall  f1-score   support

          20       0.00      0.00      0.00         5
          30       0.74      0.88      0.80      1291
          45       0.55      0.54      0.55       655
          65       0.67      0.03      0.07       230
          80       0.00      0.00      0.00         1
         120       0.33      0.07      0.12        14

    accuracy                           0.68      2196
   macro avg       0.38      0.25      0.26      2196
weighted avg       0.67      0.68      0.64      2196

[[   0    5    0    0    0    0]
 [   0 1133  157    0    0    1]
 [   0  295  356    4    0    0]
 [   0   92  129    8    0    1]
 [   0    0    1    0    0    0]
 [   0    8    5    0    0    1]]

_____

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import classification_report as cr
from sklearn.metrics import confusion_matrix as cm
train=pd.read_excel("Data_Train.xlsx")
train["Delivery_Time"]=train["Delivery_Time"].apply(lambda x : int(x.split(' ')[0].strip()))
train.drop(columns='Location',inplace=True)
train.drop(columns='Cuisines',inplace=True)
train.drop(train[train['Average_Cost']=='for'].index,inplace=True)
train.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
train.Average_Cost.astype(float)
train.Restaurant.replace('ID_','',regex=True, inplace=True)
train.Restaurant.astype(float)
train.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
train.Minimum_Order.astype(float)
train.drop(train[train['Votes']=='-'].index, inplace=True)
train.drop(train[train['Reviews']=='-'].index, inplace=True)
train.replace('NEW','0', inplace=True)
train.replace('-',np.NaN, inplace=True)
train.drop(train[(train['Rating']=="Opening Soon") | (train['Rating']=="Temporarily Closed")].index, inplace=True)
train.Rating = train.Rating.astype(float)
me=round(train.Rating.mean(skipna=True),1)
train.Rating.fillna(me, inplace=True)
train.Rating= train.Rating.astype(str)
X=train.drop(columns='Delivery_Time')
y=train.Delivery_Time
rfcl=rfc(n_estimators=100, max_depth=10, random_state=11)
rfcl=rfcl.fit(X, y)
predc=rfcl.predict(test)
print(predc)
# print(rfcl.score(test,predc))
# print(mse(test,predc))
# print(cr(test,predc))
df=pd.DataFrame(predc, columns=['Delivery_Time'])
df.Delivery_Time=df.Delivery_Time.astype(str) + ' minutes'
df.to_excel('del_time.xlsx', index=False)
# X.Rating.value_counts().sort_index()

[30 30 30 ... 30 30 30]


In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import classification_report as cr
train=pd.read_excel("Data_Train.xlsx")
test=pd.read_excel("Data_Test.xlsx")
train["Delivery_Time"]=train["Delivery_Time"].apply(lambda x : int(x.split(' ')[0].strip()))
train.drop(columns='Location',inplace=True)
test.drop(columns='Location',inplace=True)
train.drop(columns='Cuisines',inplace=True)
test.drop(columns='Cuisines',inplace=True)
train.drop(train[train['Average_Cost']=='for'].index,inplace=True)
# test.drop(test[test['Average_Cost']=='for'].index,inplace=True)
train.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
test.Average_Cost.replace('[\₹,]','',regex=True,inplace=True)
train.Average_Cost.astype(float)
test.Average_Cost.astype(float)
train.Restaurant.replace('ID_','',regex=True, inplace=True)
train.Restaurant.astype(float)
test.Restaurant.replace('ID_','',regex=True, inplace=True)
test.Restaurant.astype(float)
train.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
train.Minimum_Order.astype(float)
test.Minimum_Order.replace('[\₹,]','',regex=True, inplace=True)
test.Minimum_Order.astype(float)
# train.Rating.value_counts().sort_index()
train.drop(train[(train['Rating']=="-") | (train['Rating']=="NEW") | (train['Rating']=="Opening Soon") | (train['Rating']=="Temporarily Closed")].index, inplace=True)
train.drop(train[train['Votes']=='-'].index, inplace=True)
train.drop(train[train['Reviews']=='-'].index, inplace=True)

test.replace('NEW', np.NaN, inplace=True)
test.replace('Opening Soon', np.NaN, inplace=True)
test.replace('-',np.NaN, inplace=True)
test.Rating = test.Rating.astype(float)
me=round(test.Rating.mean(skipna=True),1)
test.Rating.fillna(me, inplace=True)
test.Rating= test.Rating.astype(str)
test.Votes.fillna('7',limit=100, inplace=True)
test.Votes.fillna('9',limit=100, inplace=True)
test.Votes.fillna('6',limit=100, inplace=True)
test.Votes.fillna('5',limit=100, inplace=True)
test.Votes.fillna('4',limit=100, inplace=True)
test.Votes.fillna('10',limit=100, inplace=True)
test.Reviews.fillna('1',limit=100, inplace=True)
test.Reviews.fillna('2',limit=100, inplace=True)
test.Reviews.fillna('3',limit=100, inplace=True)
test.Reviews.fillna('4',limit=100, inplace=True)
test.Reviews.fillna('5',limit=100, inplace=True)
test.Reviews.fillna('10',limit=100, inplace=True)
X=train.drop(columns='Delivery_Time')
y=train.Delivery_Time
# X_train, x_test, y_train, y_test=tts(X,y,test_size=0.25)
rfcl=rfc(n_estimators=100, max_depth=10, random_state=11)
rfcl=rfcl.fit(X, y)
# predc=rfcl.predict(x_test)

# print(rfcl.score(y_test,predc))
# print(mse(y_test,predc))
# print(cr(y_test,predc))
# print(len(predc))

pred_res=rfcl.predict(test)

# df=pd.DataFrame(pred_res, columns=['Delivery_Time'])
# df.Delivery_Time=df.Delivery_Time.astype(str) + ' minutes'
# df.to_excel('food_del_time.xlsx', index=False)



X_train, x_test, y_train, y_test=tts(X,y,test_size=0.25)
for col in X_train:
  X_train[[col]] = X_train[[col]].apply(pd.to_numeric)
  test[[col]] = test[[col]].apply(pd.to_numeric)
from xgboost import XGBClassifier as xgb
xgbc=xgb()
xgbc=xgbc.fit(X_train, y_train)
predxgbc = xgbc.predict(test)
df=pd.DataFrame(pred_res, columns=['Delivery_Time'])
df.Delivery_Time=df.Delivery_Time.astype(str) + ' minutes'
df.to_excel('food_del_time.xlsx', index=False)
# print('____________________________________________________________')
# print('                            XGBoost Classifier  ')
# print('____________________________________________________________')
# print('Predicted Values: ',predxgbc)
# print(xgbc.score(x_test,y_test))
# print(mse(y_test,predxgbc))
# print(cr(y_test,predxgbc))
# print(cm(y_test,predxgbc))
# print('\n____________________________________________________________\n')

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3509: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
